### ISSUE TITLE
Build Script

### ISSUE THREAD

**Issue by azzmosphere** [niallyoung/RPNCalculator_java#3]
The build.xml file should include all the dependencies such as 

It looks like you using ANT/IVY to create the project so the dependancies will need to come form there.

These can be found at https://mvnrepository.com or jcenter

**Comment by azzmosphere** [comment]
When I was trying to compile the project I noticed that I was getting compile errors,  the command I used to compile was:

```
cd RPNCalculator
ant
```
The following errors occur:

```
    [javac] Compiling 1 source file to /Users/aspiteri/Workspace/RPNCalculator/build/classes
    [javac] /Users/aspiteri/Workspace/RPNCalculator/src/rpncalculator/RPNOperators/RPNOperatorEnum.java:10: error: invalid method declaration; return type required
    [javac]         public rpnOperator() {
    [javac]                ^
    [javac] /Users/aspiteri/Workspace/RPNCalculator/src/rpncalculator/RPNOperators/RPNOperatorEnum.java:22: error: invalid method declaration; return type required
    [javac]         public rpnOperator() {
    [javac]                ^
    [javac] /Users/aspiteri/Workspace/RPNCalculator/src/rpncalculator/RPNOperators/RPNOperatorEnum.java:28: error: ';' expected
    [javac]     public RPNOperator rpnOperator {
    [javac]                                   ^
    [javac] 3 errors

BUILD FAILED
/Users/aspiteri/Workspace/RPNCalculator/nbproject/build-impl.xml:603: The following error occurred while executing this line:
/Users/aspiteri/Workspace/RPNCalculator/nbproject/build-impl.xml:245: Compile failed; see the compiler error output for details.

Total time: 0 seconds
```

**Comment by niallyoung** [comment]
NetBeans declares project dependencies elsewhere in nbproject/* - you'll need to install and use NetBeans for this to work cleanly out-of-the-box :(  I'm looking at IntelliJ vs. NetBeans at the moment and will convert the project across if I switch IDEs - disappointing that you need to pay for Spring support in IntelliJ, but the macOS version of NetBeans is pretty clunky compared to Windows so I may have to bite the bullet and buy in this financial year :)

I didn't get any compilation warnings or errors in NetBeans 7.0.1 (Windows), nor in NetBeans 8.2 (macOS). The project doesn't declare any such methods, so the errors above look like an artefact of my RPNOperatorEnum declaration in RPNController as there is no RPNOperators/RPNOperatorEnum.java file. I'll move the Enum out into its own source file and add tests soon.
