### ISSUE TITLE
Remove public modifier on interfaces

### ISSUE THREAD

**Issue by azzmosphere** [niallyoung/RPNCalculator_java#4]
https://github.com/niallyoung/RPNCalculator_java/blob/9033564de033a97a14aec8bc2af7a1cc439c0f0b/src/rpncalculator/IOperator.java#L12

The line 
```
public void execute
```

would be better written as

```
void execute
```

All methods in a interface are either public or protected therefore it is up to the class to imply scope.

**Comment by niallyoung** [comment]
Yeah I prefer to be explicit rather than rely on implicit language defaults.
