### ISSUE TITLE
Integer used instead of boolean

### ISSUE THREAD

**Issue by azzmosphere** [niallyoung/RPNCalculator_java#5]
https://github.com/niallyoung/RPNCalculator_java/blob/9033564de033a97a14aec8bc2af7a1cc439c0f0b/src/rpncalculator/RPNController.java#L55

the matched variable would be better written as a boolean type.  The keywords true and false can be used within the code.

**Comment by niallyoung** [comment]
Good catch, this is a bad habit of mine from working in languages with no first-class booleans! I'm actually going to handle this in https://github.com/niallyoung/RPNCalculator_java/issues/1 as the related continue should be a break, and I'm curious if there's a better way to break out of nested blocks like this e.g. like other language's loop labels
