### ISSUE TITLE
Overridden method without a '@Override'

### ISSUE THREAD

**Issue by azzmosphere** [niallyoung/RPNCalculator_java#6]
https://github.com/niallyoung/RPNCalculator_java/blob/9033564de033a97a14aec8bc2af7a1cc439c0f0b/src/rpncalculator/RPNOperator.java#L27

The `toString` method is part of the Object class and therefore should contain a ```@Override``` annotation, however it looks like it should not be here before.  If you need it to be complied to in the concrete class I would put it there and delete it from here.  Unless there is a use case when it should return "".

**Comment by niallyoung** [comment]
Good catch for the missing @Override!

I do want the abstract class to enforce a minimum of behaviour here, as Object's toString() returns getClass().getName() etc. which is in appropriate for this Application.

**Comment by niallyoung** [comment]
Fixed in https://github.com/niallyoung/RPNCalculator_java/commit/b229184769e26b4770d4249e2ed922c8b7c1655c
